### ISSUE TITLE
Styled variables undeclared

### ISSUE THREAD

**Issue by Nauthiz-Jera** [styled-components/webstorm-styled-components#12]
Webstorm is warning that the properties of styled are undeclared.
![screen shot 2017-09-01 at 11 06 56 am](https://user-images.githubusercontent.com/18623601/29975799-b866d1b4-8f05-11e7-9810-012e52552a66.png)

**Comment by jm90m** [comment]
Yeah I'm getting this as well

**Comment by undeadcat** [comment]
Thanks!
It's a valid issue. Missed it.

WebStorm should have been able to resovle these properties using typing information contained in .d.ts files. Created https://youtrack.jetbrains.com/issue/WEB-28565 because it's part of a more general problem related to .d.ts support.

Will also take a look next week to see if a different fix specific to this plugin is possible.

**Comment by bliitzkrieg** [comment]
I'm also experiencing this

**Comment by undeadcat** [comment]
Sorry for not replying to this earlier.
This has been fixed on the IDE side in 2017.3, in WebStorm and all IDEA-based IDEs.

Kudos to @anstarovoyt for fixing it.
I'm going to close this, if it's ok. The linked issue is still open because it's a wider problem related to support of type aliases in TypeScript.
