### ISSUE TITLE
any plans css support?

### ISSUE THREAD

**Issue by satispunk** [styled-components/webstorm-styled-components#19]
css is not yet supported?

```js
impot {css} from 'styled-components'

const styles = css`
  color: red
`
```

**Comment by undeadcat** [comment]
What result are you experiencing?
It was intended to be supported. 
But I see now that your sample has invalid red code highlights. 
![image](https://user-images.githubusercontent.com/7509842/30033190-8464ec58-91a2-11e7-91d5-23096601de88.png)

This is because it currently assumes the string to contain a complete declaration.


Could any of the styled-components experts, perhaps @daedlock, since you reviewed my PR when we added initial support clarify: is css`` intended to be used for whole css declarations, including selectors?
```css
const styles2 = css`
div {
    color: red
}
another {
    margin:5px
}
`
```` 
or sets of properties?
```css
const styles = css`
  color: red
````

IIRC correctly I've seen both kinds of usages?
Depending on that there either should or should not be a prefix/suffix added to the injected text.

**Comment by daedlock** [comment]
Yes, AFAIK, `css` selector should contain complete declaration. Please confirm @mxstbr

**Comment by mxstbr** [comment]
Not quite true. `css` is used like `styled.x`:

```JS
const styleFragment = css`
  color: blue;
`

const Button = styled.div`
  background: red;
  ${styleFragment}
`
```

That is the most widely used usage.

Note though that both _can_ (but don't have to!) also contain full CSS declarations for nesting:

```JS
const styleFragment = css`
  color: blue;
  
  // Any div within a component that has this style fragment will be red
  div {
    color: red;
  }
`

const Button = styled.div`
  background: red;
  ${styleFragment}
  
  // Any span within this button will be blue
  span {
    background: blue;
  }
`
```

(excuse the nonsensical example)

**Comment by undeadcat** [comment]
Ok, thanks, I assumed it was expected to contain a complete declaration and was wrong.
Created a PR to fix this
