### ISSUE TITLE
reformat support?

### ISSUE THREAD

**Issue by canisminor1990** [styled-components/webstorm-styled-components#22]

**Comment by undeadcat** [comment]
Unfortunately it's not clear how to implement this on the plugin side currently.
The issue is that the part of the IDEA platform responsible for formatting injected code currently does not support injections with more than one part.

There are plans to address this in future versions of IDEA.
Please follow [WEB-28540](https://youtrack.jetbrains.com/issue/WEB-28540) for updates.
