### ISSUE TITLE
import styled from 'styled-components' marked/colored as un-used

### ISSUE THREAD

**Issue by serle** [styled-components/webstorm-styled-components#42]
The styled import is not being recognized as being used by the underlying code. It is permanently colored as an unused import by the editor

**Comment by undeadcat** [comment]
@serle, This plugin does not affect analysis of JS code, only enables CSS within fragments that should be considered CSS code.

The best place for your issue would be the [WebStorm issue tracker](https://youtrack.jetbrains.com/issues?q=%23WEB).

When creating an issue, it would be helpful if you would provide the IDE version you're using, and a self-contained sample that reproduces it. I was not able to reproduce the issue just from your description in the latest 2018.1 EAP build or in 2017.3.

**Comment by skyboyer** [comment]
I was able to reproduce that with next code.

```
import styled from 'styled-components';
import App from '../../components/App'; // it does not matter what to 

const A = styled(App)`{
color: red;
}`;

export default A;
```

After I disable `webstorm-styled-components` ESLint stopped to complain. 

Surprisingly after enabling plugin again ESLint is still fine with code. So whatever happened has been fixed by disabling and enabling webstorm-styled-components.

Webstorm's version: WS-183.5429.34, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6,
