### ISSUE TITLE
IntelliJ IDEA 2018.1 doesn't recognize styled.div calls

### ISSUE THREAD

**Issue by SpearThruster** [styled-components/webstorm-styled-components#43]
This happened only after upgrading from 2017.3 to 2017.1

![issue](https://user-images.githubusercontent.com/1324069/38192579-d17486d2-366d-11e8-95e8-90c513429f68.png)

**Comment by undeadcat** [comment]
Yup, unfortunately, this is a regression on the IDE side. 
Here's the corresponding issue: https://youtrack.jetbrains.com/issue/WEB-32051

**Comment by undeadcat** [comment]
The issue was fixed on the IDE side in 2018.1.2.

If you're using WebStorm, the release build is already up on [the website](https://www.jetbrains.com/webstorm/download/#section=mac). If you're using IDEA or another IDE, [EAP builds](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2018.1+EAP) should contain the fix, a release build will be available in the next few days.
