### ISSUE TITLE
Support for "styled-components-ts"

### ISSUE THREAD

**Issue by vegetablesalad** [styled-components/webstorm-styled-components#45]
It would be great to add support for [styled-components-ts](https://github.com/jacob-ebey/styled-components-ts) library.

`import styledComponentsTS from 'styled-components-ts'`

**Comment by Sjiep** [comment]
There is currently a pull request in progress to "Allow type arguments in generic tagged templates". 

I believe the only reason styled-components-ts is there because this functionality wasn't available before, so it should become redundant once the pull request gets accepted and makes it into master.

**Comment by vegetablesalad** [comment]
Oh that's great to hear. This problem has been bothering me for a while. Thank You.
