### ISSUE TITLE
Stylelint highlighting support?

### ISSUE THREAD

**Issue by doasync** [styled-components/webstorm-styled-components#52]
[Tweet](https://twitter.com/webstormide/status/903615955032518656)
"Just need stylelint support inside and will be perfect"

**Comment by dmatteo** [comment]
Come on, let's not make VSCode win this battle, since they have it already 😂

**Comment by doasync** [comment]
The issue is only about highlighting. 
We can lint styled-components using these tools:
https://www.styled-components.com/docs/tooling#stylelint

**Comment by doasync** [comment]
I still can't see errors in IDE 😞

**Comment by doasync** [comment]
@undeadcat

**Comment by undeadcat** [comment]
This is fixed on the IDE side in 2019.1, as this affects not only styled-components, but more generally any kind of CSS in JS. 
In order to see Stylelint highlighting, enable the checkbox 'Process JS files' in Stylelint settings in the IDE.

Please see [WEB-30614](https://youtrack.jetbrains.com/issue/WEB-30614#focus=streamItem-27-3304830.0-0) for details for details and try out the feature in a 2019.1 EAP build: https://www.jetbrains.com/webstorm/eap/.

**Comment by doasync** [comment]
Thanks, it's working with the latest WebStorm 2019.1 EAP build
