### ISSUE TITLE
Expression inside parenthesis breaks parsing

### ISSUE THREAD

**Issue by tkh44** [styled-components/webstorm-styled-components#6]
Full example.

```javascript
const HeroImage = styled(Box)`
  position: relative;
  &:after {
    content: '';
    position: abs${'out'}te;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-image: url('${p => p.bgSrc}'); // <-- this breaks parsing for the rest of the block
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    border-radius: 6px;
    opacity: 0.87;
  }
`
```

Here are some screenshots. I put a random expression inside `absolute` to see if that broke it as well. (it didn't)
![image](https://user-images.githubusercontent.com/662750/29897204-08bfaac4-8d9d-11e7-9bcd-ef71228396be.png)

(with the property removed)
![image](https://user-images.githubusercontent.com/662750/29897211-138fadb4-8d9d-11e7-8c24-b04580c429c8.png)

**Comment by daedlock** [comment]
I can confirm that. Its a bit tricky to handle interpolations. Currently, the plugin filters out any interpolations amd substitute it with prefix & suffix. So fixing that is a matter of handling all positions an interpolation can appear. I already missed that it can appear between brackets which is why the SCSS parser breaks. Everyone is welcome to take the issue. If not, I will work on a fix myself in my next spare time slot.  

Thanks for reporting the issue.

**Comment by daedlock** [comment]
Fixed in https://github.com/styled-components/webstorm-styled-components/pull/7
